### ISSUE TITLE
Package structure results in multiple installed packages

### ISSUE THREAD

**Issue by bgyori** [twosixlabs-dart/dart-cli#7]
I noticed that this repository is structured such that about a dozen different packages are in the `src` folder and all these packages get installed separately as standalone packages when pip installing dart-cli. For example, folders like `auth`, `cli`, `health`, `local`, `pipeline`, `ssh`, `users`, `utilities` are very generic names that are effectively defined as Python packages. This results in a - I assume unintended - situation where after I pip install dart-cli, and do `import users` or `import ssh`, these appear as "packages" that were originally defined in `dart-cli/src`. Would it make sense to refactor the package to organize these subfolders one level deeper inside a package called `dart_cli` so that only that single package gets installed on users' Python environments? This would require changing imports such as e.g., `from utilities.auth import generate_auth_headers` to `from dart_cli.utilities.auth import generate_auth_headers` or `from ..utilities .auth import generate_auth_headers`. Let me know if you agree this would make sense, I can also help with the refactoring if that's helpful.

**Comment by johnhungerford** [comment]
Yeah we definitely need to change this, and I agree that the best way to do so would be to nest all packages within a root package. This should be a fairly quick refactor on an IDE. (I'll take care of it.)
